spring:
    application:
        name: vibe-scribe
    ai:
        openai:
            api-key: "YOUR_API_KEY"
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop # 자동으로 테이블 tkrwp
        show-sql: true  # SQL 쿼리 로그 출력
        properties:
            hibernate:
                format_sql: true
    h2:
        console:
            enabled: true
            path: /h2-console